{"name": "test_2_element_not_interactable_exception_handling", "status": "passed", "start": 1710525196751, "stop": 1710525202354, "uuid": "6f1e70c5-5d3d-4dd8-a1a9-c3350f6cc167", "historyId": "9a6e34206418c76e720e137facaa608f", "testCaseId": "9a6e34206418c76e720e137facaa608f", "fullName": "Tests.test_exception.TestLogin#test_2_element_not_interactable_exception_handling", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('setup_and_teardown', 'log_on_failure')"}, {"name": "parentSuite", "value": "Tests"}, {"name": "suite", "value": "test_exception"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-UEVTOM8"}, {"name": "thread", "value": "5224-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Tests.test_exception"}]}