{"name": "test_verify_error_notification_with_invalid_username", "status": "passed", "start": 1709473028904, "stop": 1709473029425, "uuid": "4028366e-d1bb-4e41-b919-dc9dfb0000ea", "historyId": "d5434eaee24d301aa8d9d029d1edcc34", "testCaseId": "d5434eaee24d301aa8d9d029d1edcc34", "fullName": "Tests.test_login.TestSearch#test_verify_error_notification_with_invalid_username", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('setup_and_teardown', 'log_on_failure')"}, {"name": "parentSuite", "value": "Tests"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestSearch"}, {"name": "host", "value": "DESKTOP-UEVTOM8"}, {"name": "thread", "value": "16120-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Tests.test_login"}]}