{"name": "test6_verify_error_notification_without_credentials", "status": "failed", "statusDetails": {"message": "AssertionError: Error message not found on the page", "trace": "self = <test_login.TestLogin object at 0x000001D7305504D0>\n\n    def test6_verify_error_notification_without_credentials(self):\n        assertions = json_data['assertionTexts']\n        self.page_object.verify_correct_page_loaded(assertions['successLoginPageLoad'])\n        self.page_object.click_submit()\n>       self.page_object.verify_invalid_credentials_notification(assertions['invalidUserName'])\n\nTests\\test_login.py:61: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <Pages.loginPage.Login object at 0x000001D730550E90>\nerror_text = 'Your username is invalid!'\n\n    def verify_invalid_credentials_notification(self, error_text):\n        error_message = self.driver.find_element(By.CSS_SELECTOR, errorMessageLocator).text\n>       assert error_message.__eq__(error_text), \"Error message not found on the page\"\nE       AssertionError: Error message not found on the page\n\nPages\\loginPage.py:61: AssertionError"}, "start": 1710573303334, "stop": 1710573303396, "uuid": "88893975-dd31-4170-bf9d-0c7b3ddfacf1", "historyId": "4a4759846ac445ccc3ca9b12d5490ec9", "testCaseId": "4a4759846ac445ccc3ca9b12d5490ec9", "fullName": "Tests.test_login.TestLogin#test6_verify_error_notification_without_credentials", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('setup_and_teardown', 'log_on_failure')"}, {"name": "parentSuite", "value": "Tests"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-UEVTOM8"}, {"name": "thread", "value": "4100-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Tests.test_login"}]}