{"name": "test_4_stale_element_reference_exception_handling", "status": "passed", "start": 1710526138579, "stop": 1710526143766, "uuid": "005b7820-2815-4b5a-8f4e-f6a2f2f540ef", "historyId": "0771f531fe82db7935c195624282b527", "testCaseId": "0771f531fe82db7935c195624282b527", "fullName": "Tests.test_exception.TestLogin#test_4_stale_element_reference_exception_handling", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('setup_and_teardown', 'log_on_failure')"}, {"name": "parentSuite", "value": "Tests"}, {"name": "suite", "value": "test_exception"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-UEVTOM8"}, {"name": "thread", "value": "10492-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Tests.test_exception"}]}