{"name": "test_4_stale_element_reference_exception_handling", "status": "passed", "start": 1710573223367, "stop": 1710573228442, "uuid": "c79789f4-7c1e-498e-857d-b6d0a3d3d909", "historyId": "0771f531fe82db7935c195624282b527", "testCaseId": "0771f531fe82db7935c195624282b527", "fullName": "Tests.test_exception.TestLogin#test_4_stale_element_reference_exception_handling", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('setup_and_teardown', 'log_on_failure')"}, {"name": "parentSuite", "value": "Tests"}, {"name": "suite", "value": "test_exception"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-UEVTOM8"}, {"name": "thread", "value": "4100-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Tests.test_exception"}]}