{"name": "test_4_stale_element_reference_exception_handling", "status": "passed", "start": 1709527098252, "stop": 1709527104065, "uuid": "7c6f56a3-d03d-4c2b-a343-922d7147ae96", "historyId": "0771f531fe82db7935c195624282b527", "testCaseId": "0771f531fe82db7935c195624282b527", "fullName": "Tests.test_exception.TestLogin#test_4_stale_element_reference_exception_handling", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('setup_and_teardown', 'log_on_failure')"}, {"name": "parentSuite", "value": "Tests"}, {"name": "suite", "value": "test_exception"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-UEVTOM8"}, {"name": "thread", "value": "12036-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Tests.test_exception"}]}