{"name": "test3_verify_error_notification_with_invalid_username", "status": "passed", "start": 1710525280092, "stop": 1710525280508, "uuid": "997040b6-1aff-43cd-b8f0-0b9d16ccb142", "historyId": "13cbf66d9ee9b382299ff07fb6e40447", "testCaseId": "13cbf66d9ee9b382299ff07fb6e40447", "fullName": "Tests.test_login.TestLogin#test3_verify_error_notification_with_invalid_username", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('setup_and_teardown', 'log_on_failure')"}, {"name": "parentSuite", "value": "Tests"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-UEVTOM8"}, {"name": "thread", "value": "5224-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Tests.test_login"}]}