{"name": "test_verify_error_notification_with_invalid_username", "status": "passed", "start": 1709527096312, "stop": 1709527099689, "uuid": "47e1209a-8d35-4d53-aa8c-30703d6ae67a", "historyId": "c5699d669c3cb9d254def061caeea2bc", "testCaseId": "c5699d669c3cb9d254def061caeea2bc", "fullName": "Tests.test_login.TestLogin#test_verify_error_notification_with_invalid_username", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('setup_and_teardown', 'log_on_failure')"}, {"name": "parentSuite", "value": "Tests"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-UEVTOM8"}, {"name": "thread", "value": "2832-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Tests.test_login"}]}